### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by szokodiakos** [ifml/ifml-editor#13]
Hello!

(Thank you very much for your super fast previous reply! I have updated the plugin and there are no more errors during the validation.)

Although I have encountered another issue: I would like to create a Code Generator for the IFML editor (for example an Android app generator) so I imported the plugin projects to an Eclipse (with Modeling tools) and installed Acceleo 3.5 plugin on it (because of the EditorDesign project).

However if I launch the Runtime Eclipse and import the Movie example, the IFML representation is a bit faulty (it still passes the tool's validation mechanism):

![ifmltool](https://cloud.githubusercontent.com/assets/5138121/5269669/1ee2ae58-7a65-11e4-9f0d-5dccd21ff388.png)

In the Host Eclipse the IFMLEditorDesign project shows some (precisely two) errors in the "helper.mtl" Acceleo file:

![host-acceleo-error](https://cloud.githubusercontent.com/assets/5138121/5269716/76946772-7a65-11e4-8903-043473971bbc.png)

I have looked up the Ecore metamodel and the IFMLParameter class' type attribute does have a name property, although the UMLStructuralFeature class' structuralFeature field does not have a type (if I am not mistaken). The IFML editor itself (from the update site) works perfectly, so I have no idea what am I doing wrong (unfortuanetly I have no experience with Acceleo).

Can these two problems correlate with eachother? Am I missing some plugin dependency (Fresh Eclipse Modeling Tools + Acceleo 3.5 from MarketPlace)?

Thank you in advance!

Akos

**Comment by hamzaed** [comment]
Hi Akos,

Here are the steps to follow to install the editor in development mode:
1. Install a fresh Eclipse Modeling Tools (Luna)
2. Install the plugins Sirius and Acceleo
3. Import the 3 projects : IFMLEditor, IFMLEditor.edit and IFMLEditor.editor
4.  Lunch an new Eclipse Runtime and import the project IFMLEditorDesign
5. In the second Eclipse instance you can create your own diagram or import the project from the repository.
6. Create your Acceleo code generator in the 2nd Eclipse runtime

Notes:
- IFMLEditorDesign must be imported in the 2nd eclipse runtime
- To import the projects, use a fresh eclipse which doesn't have IFML Editor plugin installed or you will get errors due to dependencies confusion (2 IFML in the runtime)

Hamza

**Comment by marcinkunert** [comment]
Hi @szokodiakos,

have you managed to figure it out? I am struggling with a very similar problem and could use some pro tips. I would love to hear from you here or per email: the.martines@gmail.com

Greetings
Marcin
